version: '3.8'

services:
  music-server:
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    build: .
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./music:/app/music
    environment:
      - PYTHONUNBUFFERED=1
